name: CI
on:
    push:
        branches:
            - master
        tags:
            - "*"
    pull_request:

jobs:
    test:
        strategy:
            fail-fast: false
            matrix:
                java: [adopt@1.11]
                os: [ubuntu-latest, windows-2025]
                scala: ["2.12.21", "2.13.18", "3.3.7"]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4
            - uses: olafurpg/setup-scala@v14
              with:
                  java-version: ${{ matrix.java }}
            - run: sbt "++${{ matrix.scala }}" ci-test
              shell: bash
    formatting:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: olafurpg/setup-scala@v14
            - run: sbt fmtCheck
